# Generated by Django 3.2 on 2021-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki_SECA', '0002_rename_problem_problem_wiki_session'),
        ('expert_questions_SECA', '0001_initial'),
        ('UserSECA', '0001_initial'),
        ('SECAAlgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predictions',
            new_name='Sessions',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='problem',
        ),
        migrations.AddField(
            model_name='notes',
            name='session',
            field=models.ManyToManyField(to='SECAAlgo.Sessions'),
        ),
    ]
