# Generated by Django 3.2 on 2021-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SECAAlgo', '0002_auto_20210624_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='confidence',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
