# Generated by Django 3.2 on 2021-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SECAAlgo', '0003_images_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='bounding_box_coordinates',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
