# Generated by Django 3.2 on 2021-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SECAAlgo', '0005_explanationset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='explanations',
            field=models.ManyToManyField(to='SECAAlgo.ExplanationSet'),
        ),
    ]
