# Generated by Django 3.2 on 2021-06-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki_SECA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem_wiki',
            old_name='problem',
            new_name='session',
        ),
    ]
