# Generated by Django 3.2 on 2021-06-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SECAAlgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('answer', models.CharField(blank=True, max_length=10000)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SECAAlgo.predictions')),
            ],
        ),
    ]
